-- Dữ liệu hộp lưu trữ (hộp có thời hạn, số 1-590)
-- thung_id được tra theo ma_thung từ file Tra cứu lưu kho.
-- Hộp chưa xếp thùng (73,74,224-236,262,339,390,455 và từ 478 trở đi): thung_id = NULL

INSERT INTO hop (so_hop, loai_hop, thung_id) VALUES
    (1, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (2, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (3, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (4, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (5, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (6, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0001')),
    (7, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (8, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (9, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (10, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (11, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (12, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0002')),
    (13, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (14, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (15, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (16, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (17, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (18, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0003')),
    (19, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (20, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (21, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (22, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (23, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (24, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0004')),
    (25, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (26, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (27, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (28, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (29, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (30, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0005')),
    (31, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (32, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (33, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (34, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (35, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (36, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0006')),
    (37, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (38, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (39, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (40, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (41, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (42, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0007')),
    (43, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (44, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (45, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (46, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (47, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (48, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0008')),
    (49, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (50, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (51, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (52, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (53, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (54, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0009')),
    (55, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (56, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (57, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (58, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (59, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (60, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0010')),
    (61, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (62, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (63, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (64, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (65, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (66, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0011')),
    (67, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (68, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (69, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (70, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (71, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (72, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0012')),
    (73, 'thoi_han', NULL),
    (74, 'thoi_han', NULL),
    (75, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (76, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (77, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (78, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (79, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (80, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0013')),
    (81, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (82, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (83, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (84, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (85, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (86, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0014')),
    (87, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (88, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (89, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (90, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (91, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (92, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0015')),
    (93, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (94, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (95, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (96, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (97, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (98, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0016')),
    (99, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (100, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (101, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (102, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (103, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (104, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0017')),
    (105, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (106, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (107, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (108, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (109, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (110, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0018')),
    (111, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (112, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (113, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (114, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (115, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (116, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0019')),
    (117, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (118, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (119, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (120, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (121, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (122, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0020')),
    (123, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (124, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (125, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (126, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (127, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (128, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0021')),
    (129, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (130, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (131, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (132, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (133, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (134, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0022')),
    (135, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (136, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (137, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (138, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (139, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (140, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0023')),
    (141, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (142, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (143, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (144, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (145, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (146, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0024')),
    (147, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (148, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (149, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (150, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (151, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (152, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0025')),
    (153, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (154, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (155, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (156, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (157, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (158, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0026')),
    (159, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (160, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (161, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (162, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (163, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (164, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0027')),
    (165, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (166, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (167, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (168, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (169, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (170, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0028')),
    (171, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (172, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (173, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (174, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (175, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (176, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0029')),
    (177, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (178, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (179, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (180, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (181, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (182, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0030')),
    (183, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (184, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (185, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (186, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (187, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (188, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0031')),
    (189, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (190, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (191, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (192, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (193, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (194, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0032')),
    (195, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (196, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (197, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (198, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (199, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (200, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0033')),
    (201, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (202, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (203, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (204, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (205, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (206, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0034')),
    (207, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (208, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (209, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (210, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (211, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (212, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0035')),
    (213, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (214, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (215, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (216, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (217, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (218, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0036')),
    (219, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (220, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (221, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (222, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (223, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (224, 'thoi_han', NULL),
    (225, 'thoi_han', NULL),
    (226, 'thoi_han', NULL),
    (227, 'thoi_han', NULL),
    (228, 'thoi_han', NULL),
    (229, 'thoi_han', NULL),
    (230, 'thoi_han', NULL),
    (231, 'thoi_han', NULL),
    (232, 'thoi_han', NULL),
    (233, 'thoi_han', NULL),
    (234, 'thoi_han', NULL),
    (235, 'thoi_han', NULL),
    (236, 'thoi_han', NULL),
    (237, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0037')),
    (238, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (239, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (240, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (241, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (242, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (243, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0038')),
    (244, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (245, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (246, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (247, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (248, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (249, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0039')),
    (250, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (251, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (252, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (253, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (254, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (255, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0040')),
    (256, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (257, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (258, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (259, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (260, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (261, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0041')),
    (262, 'thoi_han', NULL),
    (263, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (264, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (265, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (266, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (267, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (268, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0042')),
    (269, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (270, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (271, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (272, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (273, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (274, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0043')),
    (275, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (276, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (277, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (278, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (279, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (280, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0044')),
    (281, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (282, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (283, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (284, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (285, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (286, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0045')),
    (287, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (288, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (289, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (290, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (291, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (292, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0046')),
    (293, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (294, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (295, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (296, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (297, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (298, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0047')),
    (299, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (300, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (301, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (302, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (303, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (304, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0048')),
    (305, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (306, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (307, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (308, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (309, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (310, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0049')),
    (311, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (312, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (313, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (314, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (315, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (316, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0050')),
    (317, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (318, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (319, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (320, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (321, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (322, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0051')),
    (323, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (324, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (325, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (326, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (327, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (328, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0052')),
    (329, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (330, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (331, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (332, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (333, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (334, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0053')),
    (335, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (336, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (337, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (338, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (339, 'thoi_han', NULL),
    (340, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (341, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0054')),
    (342, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (343, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (344, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (345, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (346, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (347, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0055')),
    (348, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (349, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (350, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (351, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (352, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (353, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0056')),
    (354, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (355, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (356, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (357, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (358, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (359, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0057')),
    (360, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0058')),
    (361, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0058')),
    (362, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (363, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (364, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (365, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (366, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (367, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (368, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0061')),
    (369, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (370, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (371, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (372, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (373, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (374, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (375, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0062')),
    (376, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (377, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (378, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (379, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (380, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (381, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (382, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0063')),
    (383, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (384, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (385, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (386, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (387, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (388, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (389, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0064')),
    (390, 'thoi_han', NULL),
    (391, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (392, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (393, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (394, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (395, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (396, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0065')),
    (397, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (398, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (399, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (400, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (401, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (402, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (403, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0066')),
    (404, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (405, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (406, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (407, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (408, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (409, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (410, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0067')),
    (411, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (412, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (413, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (414, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (415, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (416, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (417, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0068')),
    (418, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (419, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (420, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (421, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (422, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (423, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (424, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0069')),
    (425, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (426, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (427, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (428, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (429, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (430, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (431, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0070')),
    (432, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (433, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (434, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (435, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (436, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (437, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (438, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0071')),
    (439, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (440, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (441, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (442, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (443, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (444, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (445, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0072')),
    (446, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (447, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (448, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (449, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (450, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (451, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (452, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0073')),
    (453, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (454, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (455, 'thoi_han', NULL),
    (456, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (457, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (458, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (459, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0074')),
    (460, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (461, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (462, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (463, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (464, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (465, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0075')),
    (466, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (467, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (468, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (469, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (470, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (471, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0076')),
    (472, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (473, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (474, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (475, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (476, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (477, 'thoi_han', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0077')),
    (478, 'thoi_han', NULL),
    (479, 'thoi_han', NULL),
    (480, 'thoi_han', NULL),
    (481, 'thoi_han', NULL),
    (482, 'thoi_han', NULL),
    (483, 'thoi_han', NULL),
    (484, 'thoi_han', NULL),
    (485, 'thoi_han', NULL),
    (486, 'thoi_han', NULL),
    (487, 'thoi_han', NULL),
    (488, 'thoi_han', NULL),
    (489, 'thoi_han', NULL),
    (490, 'thoi_han', NULL),
    (491, 'thoi_han', NULL),
    (492, 'thoi_han', NULL),
    (493, 'thoi_han', NULL),
    (494, 'thoi_han', NULL),
    (495, 'thoi_han', NULL),
    (496, 'thoi_han', NULL),
    (497, 'thoi_han', NULL),
    (498, 'thoi_han', NULL),
    (499, 'thoi_han', NULL),
    (500, 'thoi_han', NULL),
    (501, 'thoi_han', NULL),
    (502, 'thoi_han', NULL),
    (503, 'thoi_han', NULL),
    (504, 'thoi_han', NULL),
    (505, 'thoi_han', NULL),
    (506, 'thoi_han', NULL),
    (507, 'thoi_han', NULL),
    (508, 'thoi_han', NULL),
    (509, 'thoi_han', NULL),
    (510, 'thoi_han', NULL),
    (511, 'thoi_han', NULL),
    (512, 'thoi_han', NULL),
    (513, 'thoi_han', NULL),
    (514, 'thoi_han', NULL),
    (515, 'thoi_han', NULL),
    (516, 'thoi_han', NULL),
    (517, 'thoi_han', NULL),
    (518, 'thoi_han', NULL),
    (519, 'thoi_han', NULL),
    (520, 'thoi_han', NULL),
    (521, 'thoi_han', NULL),
    (522, 'thoi_han', NULL),
    (523, 'thoi_han', NULL),
    (524, 'thoi_han', NULL),
    (525, 'thoi_han', NULL),
    (526, 'thoi_han', NULL),
    (527, 'thoi_han', NULL),
    (528, 'thoi_han', NULL),
    (529, 'thoi_han', NULL),
    (530, 'thoi_han', NULL),
    (531, 'thoi_han', NULL),
    (532, 'thoi_han', NULL),
    (533, 'thoi_han', NULL),
    (534, 'thoi_han', NULL),
    (535, 'thoi_han', NULL),
    (536, 'thoi_han', NULL),
    (537, 'thoi_han', NULL),
    (538, 'thoi_han', NULL),
    (539, 'thoi_han', NULL),
    (540, 'thoi_han', NULL),
    (541, 'thoi_han', NULL),
    (542, 'thoi_han', NULL),
    (543, 'thoi_han', NULL),
    (544, 'thoi_han', NULL),
    (545, 'thoi_han', NULL),
    (546, 'thoi_han', NULL),
    (547, 'thoi_han', NULL),
    (548, 'thoi_han', NULL),
    (549, 'thoi_han', NULL),
    (550, 'thoi_han', NULL),
    (551, 'thoi_han', NULL),
    (552, 'thoi_han', NULL),
    (553, 'thoi_han', NULL),
    (554, 'thoi_han', NULL),
    (555, 'thoi_han', NULL),
    (556, 'thoi_han', NULL),
    (557, 'thoi_han', NULL),
    (558, 'thoi_han', NULL),
    (559, 'thoi_han', NULL),
    (560, 'thoi_han', NULL),
    (561, 'thoi_han', NULL),
    (562, 'thoi_han', NULL),
    (563, 'thoi_han', NULL),
    (564, 'thoi_han', NULL),
    (565, 'thoi_han', NULL),
    (566, 'thoi_han', NULL),
    (567, 'thoi_han', NULL),
    (568, 'thoi_han', NULL),
    (569, 'thoi_han', NULL),
    (570, 'thoi_han', NULL),
    (571, 'thoi_han', NULL),
    (572, 'thoi_han', NULL),
    (573, 'thoi_han', NULL),
    (574, 'thoi_han', NULL),
    (575, 'thoi_han', NULL),
    (576, 'thoi_han', NULL),
    (577, 'thoi_han', NULL),
    (578, 'thoi_han', NULL),
    (579, 'thoi_han', NULL),
    (580, 'thoi_han', NULL),
    (581, 'thoi_han', NULL),
    (582, 'thoi_han', NULL),
    (583, 'thoi_han', NULL),
    (584, 'thoi_han', NULL),
    (585, 'thoi_han', NULL),
    (586, 'thoi_han', NULL),
    (587, 'thoi_han', NULL),
    (588, 'thoi_han', NULL),
    (589, 'thoi_han', NULL),
    (590, 'thoi_han', NULL)
ON CONFLICT (so_hop, loai_hop) DO NOTHING;

-- Hộp VĨNH VIỄN (đánh số riêng) ghi nhận được từ file lưu kho: hộp 13,14,15 trong thùng VTVP-0058
INSERT INTO hop (so_hop, loai_hop, thung_id) VALUES
    (13, 'vinh_vien', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0058')),
    (14, 'vinh_vien', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0058')),
    (15, 'vinh_vien', (SELECT id FROM thung WHERE ma_thung = 'VTVP-0058'))
ON CONFLICT (so_hop, loai_hop) DO NOTHING;